MySqlCommand = _csharp_getAssemblyType("LuaBuildEvents.MySql.LuaMySqlCommand")
MySqlConnection = _csharp_getAssemblyType("LuaBuildEvents.MySql.LuaMySqlConnection")
MySqlDataReader = _csharp_getAssemblyType("LuaBuildEvents.MySql.LuaMySqlDataReader")
MySqlParameters = _csharp_getAssemblyType("LuaBuildEvents.MySql.LuaMySqlParameters")
MySqlTransaction = _csharp_getAssemblyType("LuaBuildEvents.MySql.LuaMySqlTransaction")