require("lua.io")
require("lua.system")
require("lua.net")
require("lua.security")

data = File.readAllText([[C:\Users\jpdante\source\repos\LuaBuildEvents\LuaBuildEvents.Test\lua\test_all.lua]])
print(data)

co = coroutine.create(function()
    print("hi")
end)
print("\n")
print(co)
print("\n")
coroutine.resume(co)